# Generated by Django 3.2.22 on 2024-03-17 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance_app', '0002_amb_location_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_data',
            name='ambulance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ambulance_app.ambulance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_data',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ambulance_app.hospital'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance_app.ambulance')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance_app.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='emergency_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance_app.ambulance')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance_app.hospital')),
            ],
        ),
    ]
